import type { Level, CellType } from "../types";

const D = "floor_dirty" as CellType;
const C = "floor_clean" as CellType;
const W = "wall" as CellType;
const F = "furniture" as CellType;
const G = "garbage" as CellType;

export const levels: Level[] = [
  {
    id: 1,
    name: "First Clean",
    description: "Vacuum the hallway — just move and vacuum!",
    hint: "move(1) moves one tile. vacuum() cleans the tile you're on.",
    grid: [
      [W, W, W, W, W, W],
      [W, C, D, D, D, W],
      [W, W, W, W, W, W],
    ],
    start: { row: 1, col: 1 },
    startDirection: "right",
    availableCommands: ["move", "vacuum"],
    threeStarMoves: 6,
    twoStarMoves: 10,
  },
  {
    id: 2,
    name: "L-Shaped Room",
    description: "Turn the corner and keep cleaning!",
    hint: "Use turnRight() to change direction.",
    grid: [
      [W, W, W, W, W],
      [W, C, D, D, W],
      [W, W, W, D, W],
      [W, W, W, D, W],
      [W, W, W, W, W],
    ],
    start: { row: 1, col: 1 },
    startDirection: "right",
    availableCommands: ["move", "vacuum", "turnRight"],
    threeStarMoves: 8,
    twoStarMoves: 12,
  },
  {
    id: 3,
    name: "Both Ways",
    description: "Clean left and right of the start!",
    hint: "Clean one direction, then turnAround() and clean the other.",
    grid: [
      [W, W, W, W, W, W, W],
      [W, D, D, C, D, D, W],
      [W, W, W, W, W, W, W],
    ],
    start: { row: 1, col: 3 },
    startDirection: "right",
    availableCommands: ["move", "vacuum", "turnLeft", "turnRight", "turnAround"],
    threeStarMoves: 10,
    twoStarMoves: 14,
  },
  {
    id: 4,
    name: "Repeat After Me",
    description: "That's a long hallway... use repeat!",
    hint: "repeat(6) { move(1); vacuum() } is much shorter than typing it all out.",
    grid: [
      [W, W, W, W, W, W, W, W, W],
      [W, C, D, D, D, D, D, D, W],
      [W, W, W, W, W, W, W, W, W],
    ],
    start: { row: 1, col: 1 },
    startDirection: "right",
    availableCommands: ["move", "vacuum", "repeat"],
    threeStarMoves: 6,
    twoStarMoves: 14,
  },
  {
    id: 5,
    name: "Square Room",
    description: "Clean the edges of a square room using repeat!",
    hint: "repeat(4) { repeat(3) { move(1); vacuum() }; turnRight() }",
    grid: [
      [W, W, W, W, W, W],
      [W, C, D, D, D, W],
      [W, D, F, F, D, W],
      [W, D, F, F, D, W],
      [W, D, D, D, D, W],
      [W, W, W, W, W, W],
    ],
    start: { row: 1, col: 1 },
    startDirection: "right",
    availableCommands: ["move", "vacuum", "turnRight", "repeat"],
    threeStarMoves: 16,
    twoStarMoves: 22,
  },
  {
    id: 6,
    name: "Garbage Day",
    description: "Pick up all the garbage!",
    hint: "Use collect() to pick up garbage on your tile.",
    grid: [
      [W, W, W, W, W, W],
      [W, C, G, C, G, W],
      [W, C, C, C, C, W],
      [W, G, C, G, C, W],
      [W, W, W, W, W, W],
    ],
    start: { row: 1, col: 1 },
    startDirection: "right",
    availableCommands: ["move", "collect", "turnLeft", "turnRight", "repeat"],
    threeStarMoves: 14,
    twoStarMoves: 20,
  },
  {
    id: 7,
    name: "Smart Vacuum",
    description: "Use while(!roomClean()) to keep going until done!",
    hint: "while (!roomClean()) { vacuum(); move(1) } — but watch for walls!",
    grid: [
      [W, W, W, W, W, W, W],
      [W, C, D, D, D, D, W],
      [W, W, W, W, W, W, W],
    ],
    start: { row: 1, col: 1 },
    startDirection: "right",
    availableCommands: ["move", "vacuum", "turnLeft", "turnRight", "while_loop", "dirty", "wallAhead", "roomClean"],
    threeStarMoves: 5,
    twoStarMoves: 10,
  },
  {
    id: 8,
    name: "Wall Aware",
    description: "Check for walls before moving!",
    hint: "while (!roomClean()) { if (wallAhead()) { turnRight() } else { move(1); vacuum() } }",
    grid: [
      [W, W, W, W, W, W],
      [W, C, D, D, D, W],
      [W, D, D, D, D, W],
      [W, D, D, D, D, W],
      [W, D, D, D, D, W],
      [W, W, W, W, W, W],
    ],
    start: { row: 1, col: 1 },
    startDirection: "right",
    availableCommands: ["move", "vacuum", "turnLeft", "turnRight", "while_loop", "if_stmt", "dirty", "wallAhead", "roomClean"],
    threeStarMoves: 24,
    twoStarMoves: 35,
  },
  {
    id: 9,
    name: "Furnished Room",
    description: "Navigate around furniture to clean everything!",
    hint: "Combine wallAhead() with turns to go around obstacles.",
    grid: [
      [W, W, W, W, W, W, W],
      [W, C, D, D, D, D, W],
      [W, D, F, F, D, D, W],
      [W, D, D, D, D, D, W],
      [W, D, D, F, F, D, W],
      [W, D, D, D, D, D, W],
      [W, W, W, W, W, W, W],
    ],
    start: { row: 1, col: 1 },
    startDirection: "right",
    availableCommands: ["move", "vacuum", "turnLeft", "turnRight", "turnAround", "repeat", "while_loop", "if_stmt", "dirty", "wallAhead", "roomClean"],
    threeStarMoves: 35,
    twoStarMoves: 50,
  },
  {
    id: 10,
    name: "Mixed Mess",
    description: "Dirt AND garbage — vacuum and collect!",
    hint: "Check dirty() and garbageHere() to decide what to do.",
    grid: [
      [W, W, W, W, W, W, W],
      [W, C, D, G, D, D, W],
      [W, D, F, F, D, G, W],
      [W, G, D, D, D, D, W],
      [W, D, D, G, D, D, W],
      [W, W, W, W, W, W, W],
    ],
    start: { row: 1, col: 1 },
    startDirection: "right",
    availableCommands: ["move", "vacuum", "collect", "turnLeft", "turnRight", "turnAround", "repeat", "while_loop", "if_stmt", "dirty", "wallAhead", "garbageHere", "roomClean"],
    threeStarMoves: 30,
    twoStarMoves: 45,
  },
  {
    id: 11,
    name: "The Apartment",
    description: "Two rooms connected by a doorway. Clean both!",
    hint: "Clean one room, find the door, move to the next room, clean it.",
    grid: [
      [W, W, W, W, W, W, W, W, W],
      [W, D, D, D, W, D, D, D, W],
      [W, D, D, D, W, D, D, D, W],
      [W, D, D, D, C, D, D, D, W],
      [W, D, D, D, W, D, D, D, W],
      [W, W, W, W, W, W, W, W, W],
    ],
    start: { row: 3, col: 4 },
    startDirection: "left",
    availableCommands: ["move", "vacuum", "turnLeft", "turnRight", "turnAround", "repeat", "while_loop", "if_stmt", "dirty", "wallAhead", "roomClean"],
    threeStarMoves: 40,
    twoStarMoves: 55,
  },
  {
    id: 12,
    name: "Maze Clean",
    description: "Navigate a maze and clean every tile!",
    hint: "The right-hand rule: always turn right when you can, go straight when you can, turn left when you must.",
    grid: [
      [W, W, W, W, W, W, W, W],
      [W, C, D, W, D, D, D, W],
      [W, W, D, W, D, W, D, W],
      [W, D, D, D, D, W, D, W],
      [W, D, W, W, W, W, D, W],
      [W, D, D, D, D, D, D, W],
      [W, W, W, W, W, W, W, W],
    ],
    start: { row: 1, col: 1 },
    startDirection: "right",
    availableCommands: ["move", "vacuum", "turnLeft", "turnRight", "turnAround", "repeat", "while_loop", "if_stmt", "dirty", "wallAhead", "roomClean"],
    threeStarMoves: 30,
    twoStarMoves: 45,
  },
  // ---------- Levels 13–20 ----------
  {
    id: 13,
    name: "Zigzag Clean",
    description: "Clean every tile in this zigzag-shaped room using a snake pattern!",
    hint: "Clean a row going right, step down, then clean the next row going left. repeat(3) { ... } covers 3 pairs of rows.",
    grid: [
      [W, W, W, W, W, W, W, W],
      [W, C, D, D, D, D, D, W],
      [W, W, W, W, W, W, D, W],
      [W, D, D, D, D, D, D, W],
      [W, D, W, W, W, W, W, W],
      [W, D, D, D, D, D, D, W],
      [W, W, W, W, W, W, D, W],
      [W, D, D, D, D, D, D, W],
      [W, W, W, W, W, W, W, W],
    ],
    start: { row: 1, col: 1 },
    startDirection: "right",
    availableCommands: ["move", "vacuum", "turnLeft", "turnRight", "turnAround", "repeat", "while_loop", "if_stmt", "dirty", "wallAhead", "roomClean"],
    threeStarMoves: 34,
    twoStarMoves: 48,
  },
  {
    id: 14,
    name: "Garbage Sorter",
    description: "Dirt AND garbage are scattered everywhere — use the right action for each!",
    hint: "Check each tile: if (dirty()) { vacuum() } then if (garbageHere()) { collect() }. Combine with a while loop and wall checks.",
    grid: [
      [W, W, W, W, W, W, W],
      [W, C, G, D, G, D, W],
      [W, D, D, G, D, G, W],
      [W, G, D, D, G, D, W],
      [W, D, G, D, D, D, W],
      [W, W, W, W, W, W, W],
    ],
    start: { row: 1, col: 1 },
    startDirection: "right",
    availableCommands: ["move", "vacuum", "collect", "turnLeft", "turnRight", "turnAround", "repeat", "while_loop", "if_stmt", "dirty", "wallAhead", "garbageHere", "roomClean"],
    threeStarMoves: 32,
    twoStarMoves: 48,
  },
  {
    id: 15,
    name: "The Office",
    description: "Navigate narrow corridors between furniture clusters to clean everything!",
    hint: "Move carefully through the gaps between desks. Use wallAhead() to avoid bumping into furniture.",
    grid: [
      [W, W, W, W, W, W, W, W, W],
      [W, C, D, D, F, F, D, D, W],
      [W, D, D, D, F, F, D, D, W],
      [W, D, D, D, D, D, D, D, W],
      [W, D, F, F, D, D, F, F, W],
      [W, D, F, F, D, D, F, F, W],
      [W, D, D, D, D, D, D, D, W],
      [W, W, W, W, W, W, W, W, W],
    ],
    start: { row: 1, col: 1 },
    startDirection: "right",
    availableCommands: ["move", "vacuum", "turnLeft", "turnRight", "turnAround", "repeat", "while_loop", "if_stmt", "dirty", "wallAhead", "roomClean"],
    threeStarMoves: 42,
    twoStarMoves: 60,
  },
  {
    id: 16,
    name: "Hotel Hallway",
    description: "A long corridor with rooms on each side. Enter each room, clean it, and return!",
    hint: "Walk down the corridor. At each opening, turn in, clean, turn around, come back out, and continue. Use repeat for each room pair.",
    grid: [
      [W, W, D, W, W, D, W, W, D, W, W],
      [W, W, D, W, W, D, W, W, D, W, W],
      [W, C, D, D, D, D, D, D, D, D, W],
      [W, W, D, W, W, D, W, W, D, W, W],
      [W, W, D, W, W, D, W, W, D, W, W],
      [W, W, W, W, W, W, W, W, W, W, W],
    ],
    start: { row: 2, col: 1 },
    startDirection: "right",
    availableCommands: ["move", "vacuum", "turnLeft", "turnRight", "turnAround", "repeat", "while_loop", "if_stmt", "dirty", "wallAhead", "roomClean"],
    threeStarMoves: 54,
    twoStarMoves: 75,
  },
  {
    id: 17,
    name: "Dense Furniture",
    description: "Furniture everywhere! Thread through the narrow 1-tile gaps to reach every dirty tile.",
    hint: "Use wallAhead() + turns to weave between furniture. A while loop with careful turning logic is key.",
    grid: [
      [W, W, W, W, W, W, W, W],
      [W, C, F, D, F, D, F, W],
      [W, D, F, D, F, D, F, W],
      [W, D, D, D, D, D, D, W],
      [W, F, D, F, D, F, D, W],
      [W, F, D, F, D, F, D, W],
      [W, D, D, D, D, D, D, W],
      [W, W, W, W, W, W, W, W],
    ],
    start: { row: 1, col: 1 },
    startDirection: "down",
    availableCommands: ["move", "vacuum", "turnLeft", "turnRight", "turnAround", "repeat", "while_loop", "if_stmt", "dirty", "wallAhead", "roomClean"],
    threeStarMoves: 38,
    twoStarMoves: 55,
  },
  {
    id: 18,
    name: "Three Rooms",
    description: "Three connected rooms — clean all of them systematically!",
    hint: "Clean the first room, pass through the doorway, clean the middle room, pass through the next doorway, then clean the last room.",
    grid: [
      [W, W, W, W, W, W, W, W, W, W, W, W, W],
      [W, D, D, D, W, D, D, D, W, D, D, D, W],
      [W, D, D, D, W, D, D, D, W, D, D, D, W],
      [W, D, D, D, C, D, D, D, C, D, D, D, W],
      [W, D, D, D, W, D, D, D, W, D, D, D, W],
      [W, W, W, W, W, W, W, W, W, W, W, W, W],
    ],
    start: { row: 3, col: 4 },
    startDirection: "left",
    availableCommands: ["move", "vacuum", "turnLeft", "turnRight", "turnAround", "repeat", "while_loop", "if_stmt", "dirty", "wallAhead", "roomClean"],
    threeStarMoves: 52,
    twoStarMoves: 72,
  },
  {
    id: 19,
    name: "The Mansion",
    description: "A grand 10x10 mansion with furniture, dirt, and garbage. The ultimate cleaning challenge!",
    hint: "Combine everything you've learned: snake pattern for open areas, if checks for dirt vs garbage, wallAhead() to navigate around furniture.",
    grid: [
      [W, W, W, W, W, W, W, W, W, W, W, W],
      [W, C, D, D, D, D, D, D, G, D, D, W],
      [W, D, F, F, D, D, D, F, F, D, D, W],
      [W, D, D, D, D, G, D, D, D, D, G, W],
      [W, D, D, F, D, D, D, D, F, D, D, W],
      [W, G, D, F, D, D, G, D, F, D, D, W],
      [W, D, D, D, D, D, D, D, D, D, D, W],
      [W, D, F, D, D, F, F, D, D, F, D, W],
      [W, D, D, D, G, D, D, D, G, D, D, W],
      [W, D, D, D, D, D, D, D, D, D, D, W],
      [W, W, W, W, W, W, W, W, W, W, W, W],
    ],
    start: { row: 1, col: 1 },
    startDirection: "right",
    availableCommands: ["move", "vacuum", "collect", "turnLeft", "turnRight", "turnAround", "repeat", "while_loop", "if_stmt", "dirty", "wallAhead", "garbageHere", "roomClean"],
    threeStarMoves: 80,
    twoStarMoves: 110,
  },
  {
    id: 20,
    name: "Algorithm Master",
    description: "Only a wall-following algorithm can clean this twisting maze. Use the right-hand rule!",
    hint: "Right-hand rule: Try turnRight()+move(1) first. If wall ahead after turning right, undo with turnLeft() and try move(1) straight. If still blocked, turnLeft(). Repeat while (!roomClean()).",
    grid: [
      [W, W, W, W, W, W, W, W, W, W],
      [W, C, W, D, D, D, W, D, D, W],
      [W, D, W, D, W, D, W, D, W, W],
      [W, D, W, D, W, D, D, D, D, W],
      [W, D, D, D, W, W, W, W, D, W],
      [W, W, W, D, D, D, D, W, D, W],
      [W, D, D, D, W, W, D, W, D, W],
      [W, D, W, W, W, D, D, D, D, W],
      [W, D, D, D, D, D, W, W, W, W],
      [W, W, W, W, W, W, W, W, W, W],
    ],
    start: { row: 1, col: 1 },
    startDirection: "down",
    availableCommands: ["move", "vacuum", "turnLeft", "turnRight", "turnAround", "repeat", "while_loop", "if_stmt", "dirty", "wallAhead", "roomClean"],
    threeStarMoves: 55,
    twoStarMoves: 80,
  },
];

export const SANDBOX_LEVEL_ID = 99;

export function createSandboxLevel(grid: CellType[][]): Level {
  return {
    id: SANDBOX_LEVEL_ID,
    name: "Sandbox",
    description: "Your playground! Draw a room and program freely.",
    hint: "There are no rules — experiment and have fun!",
    grid,
    start: { row: 1, col: 1 },
    startDirection: "right",
    availableCommands: ["move", "vacuum", "collect", "turnLeft", "turnRight", "turnAround", "repeat", "while_loop", "if_stmt", "dirty", "wallAhead", "garbageHere", "roomClean"],
    threeStarMoves: 999,
    twoStarMoves: 999,
  };
}

export function defaultSandboxGrid(): CellType[][] {
  // 8x8 room with walls around the edge, all dirty inside
  const size = 8;
  const grid: CellType[][] = [];
  for (let r = 0; r < size; r++) {
    const row: CellType[] = [];
    for (let c = 0; c < size; c++) {
      if (r === 0 || r === size - 1 || c === 0 || c === size - 1) row.push("wall");
      else if (r === 1 && c === 1) row.push("floor_clean");
      else row.push("floor_dirty");
    }
    grid.push(row);
  }
  return grid;
}
